opensquare-network/bounties

- site/src/components/Bounty/BountyItem.js
- site/src/components/Bounty/BountyList.js
- site/src/components/Bounty/styled/bounty.js
- site/src/components/Bounty/styled/bountyLoading.js
- site/src/pages/Home.js
- site/src/store/reducers/bountySlice.js
> feat: home page stage 2

- site/package.json
- site/public/imgs/icons/add.svg
- site/src/pages/Home.js
- site/yarn.lock
> feat: home page stage 3

- site/package.json
- site/src/components/Bounty/Detail/Meta/Info.js
- site/yarn.lock
> fix: curator ellipsis

- site/src/components/Accordion.js
> fix: accordion wrap caret

- site/src/components/Bounty/BountyNoData.js
- site/src/components/Bounty/styled/bounty.js
- site/src/pages/Home.js
> fix: no data bg

- site/src/components/Bounty/BountyList.js
- site/src/components/Bounty/styled/bounty.js
> fix: ellipsis bounty title

- site/src/App.js
- site/src/components/Notification/NotificationItem.js
- site/src/components/Notification/NotificationTabs.js
- site/src/pages/Notifications.js
- site/src/store/reducers/index.js
- site/src/store/reducers/notificationSlice.js
- site/src/utils/useNotifications.js
> feat: page notification

- site/package.json
- site/src/components/Bounty/Detail/ChildBounties/index.js
- site/src/components/Bounty/Detail/index.js
- site/yarn.lock
> feat: bounty detail child bounties 1

- site/src/App.js
- site/src/components/Bounty/Detail/ChildBounties/index.js
- site/src/components/Bounty/Import/BountyLogo.js
- site/src/components/Bounty/Import/styled.js
- site/src/components/ChildBounty/Import/BountySkills.js
- site/src/components/ChildBounty/Import/index.js
- site/src/components/Common/Import/BountyMeta.js
- site/src/components/Common/Import/InputBountyId.js
- site/src/components/Common/Import/InputDescription.js
- site/src/components/Common/Import/InputTitle.js
- site/src/components/Common/Import/styled.js
- site/src/pages/ImportChildBounty.js
- site/src/utils/constants.js
> Implement import child bounty UI

- site/src/components/Bounty/BountyItem.js
> fix: bounty child bounties count

- site/src/components/ChildBounty/Detail/Applicants/index.js
> fix: child bounty detail applicants

- site/src/components/ChildBounty/Detail/Meta/Info/InfoParentBounty.js
> fix: child bounty detail meta parent bounty title

- site/src/components/Bounty/BountyItem.js
- site/src/components/Bounty/Detail/ChildBounties/index.js
- site/src/components/Bounty/Detail/ChildBounties/styled.js
- site/src/components/Bounty/Detail/Meta/Info/InfoChildBounties.js
- site/src/utils/route.js
> fix: bounty detail child bounties

- site/src/components/Bounty/StatusLabel/index.js
- site/src/components/ChildBounty/Detail/Applicants/index.js
- site/src/components/ChildBounty/Detail/Applicants/styled.js
- site/src/components/ChildBounty/Detail/Meta/actions/curator/assigned/index.js
- site/src/components/ChildBounty/Detail/Meta/actions/curator/collectingApplicant/index.js
- site/src/components/ChildBounty/Detail/Meta/actions/curator/useUnassignButton.js
- site/src/components/ChildBounty/Detail/Meta/actions/hunter/apply/index.js
- site/src/components/ChildBounty/Detail/Meta/actions/hunter/assigned/index.js
- site/src/components/ChildBounty/Detail/Meta/actions/hunter/submit/index.js
- site/src/components/ChildBounty/Detail/Meta/actions/hunter/submitted/index.js
- site/src/components/ChildBounty/Detail/Meta/actions/hunter/useCancelButton.js
- site/src/components/ChildBounty/Detail/Meta/actions/index.js
- site/src/components/ChildBounty/Detail/Meta/actions/useActionService.js
- site/src/components/ChildBounty/Detail/Meta/actions/utils.js
- site/src/hooks/useAccount.js
- site/src/hooks/useWorkflowActionService.js
- site/src/utils/constants.js
> feat: child bounty workflow 2

- site/src/components/ChildBounty/Detail/Applicants/index.js
- site/src/components/ChildBounty/Detail/Meta/actions/curator/assigned/index.js
- site/src/components/ChildBounty/Detail/Meta/actions/hunter/apply/index.js
- site/src/components/ChildBounty/Detail/Meta/actions/hunter/assigned/index.js
- site/src/components/ChildBounty/Detail/Meta/actions/index.js
- site/src/components/ChildBounty/Detail/index.js
- site/src/hooks/useWorkflowActionService.js
> Refresh data after action

- site/src/components/Bounty/Detail/ChildBounties/index.js
> fix: bounty empty child bounties

- site/src/components/ChildBounty/Detail/Applicants/index.js
- site/src/components/ChildBounty/Detail/Meta/actions/curator/assigned/index.js
- site/src/components/ChildBounty/Detail/Meta/actions/hunter/assigned/acceptAndStart.js
- site/src/components/ChildBounty/Detail/Meta/actions/hunter/assigned/index.js
- site/src/components/ChildBounty/Detail/Meta/actions/hunter/assigned/started.js
- site/src/components/ChildBounty/Detail/Meta/actions/hunter/assigned/submitted.js
- site/src/components/ChildBounty/Detail/Meta/actions/hunter/assigned/useSubmitModal.js
- site/src/components/ChildBounty/Detail/Meta/actions/hunter/open/index.js
- site/src/components/ChildBounty/Detail/Meta/actions/hunter/useCancelButton.js
- site/src/components/ChildBounty/Detail/Meta/actions/utils.js
- site/src/components/ChildBounty/Detail/Meta/index.js
- site/src/hooks/useWorkflowActionService.js
> feat: child bounty workflow 6

- site/src/components/ChildBounty/Detail/Applicants/index.js
- site/src/components/ChildBounty/Detail/Applicants/styled.js
- site/src/components/ChildBounty/Detail/Meta/actions/curator/assigned/index.js
- site/src/components/ChildBounty/Detail/Meta/actions/curator/closed/index.js
- site/src/components/ChildBounty/Detail/Meta/actions/curator/open/index.js
- site/src/components/ChildBounty/Detail/Meta/actions/hunter/assigned/acceptAndStart.js
- site/src/components/ChildBounty/Detail/Meta/actions/hunter/assigned/index.js
- site/src/components/ChildBounty/Detail/Meta/actions/hunter/assigned/started.js
- site/src/components/ChildBounty/Detail/Meta/actions/hunter/assigned/submitted.js
- site/src/components/ChildBounty/Detail/Meta/actions/hunter/open/index.js
- site/src/components/ChildBounty/Detail/Meta/actions/hunter/useCancelButton.js
- site/src/components/ChildBounty/Detail/Meta/actions/index.js
- site/src/components/ChildBounty/Detail/Meta/index.js
- site/src/components/ChildBounty/Detail/index.js
- site/src/hooks/useFetchChildBountyDetail.js
- site/src/hooks/useWorkflowActionService.js
- site/src/pages/ChildBountyDetail.js
- site/src/store/reducers/childBountyDetailSlice.js
- site/src/store/reducers/index.js
- refactor: too deep to pass a reload data fn
> feat: child bounty workflow 7

- site/src/components/ChildBounty/Detail/Applicants/index.js
- site/src/components/ChildBounty/Detail/Applicants/styled.js
> fix: curator hover applicant to assign

- site/src/components/Bounty/Import/index.js
- site/src/components/Common/Import/InputBountyId.js
> fix: import bounty id keep focus

- site/src/components/Bounty/Detail/ChildBounties/index.js
- site/src/components/Bounty/Detail/Discussions/index.js
- site/src/components/Bounty/Detail/Meta/Description.js
- site/src/components/ChildBounty/Detail/Applicants/index.js
- site/src/components/ChildBounty/Detail/Discussions/index.js
- site/src/hooks/useBountyPermission.js
- site/src/hooks/usePermission.js
> fix: bounty permission

- site/src/components/Bounty/Detail/Meta/Action/ClosedBountyCuratorActions.js
- site/src/components/Bounty/Detail/Meta/Action/OpenBountyCuratorActions.js
- site/src/components/Bounty/Detail/Meta/Action/index.js
> fix: bounty detail action button

- site/package.json
- site/src/components/Bounty/ChildBountyItem/index.js
- site/src/components/Bounty/ChildBountyItem/styled.js
- site/src/components/Bounty/Detail/Meta/Info/styled.js
- site/src/components/Bounty/Detail/index.js
- site/src/components/Bounty/Import/styled.js
- site/src/components/ChildBounty/Detail/MetaEdit/index.js
- site/src/components/ChildBounty/Detail/index.js
- site/yarn.lock
> fix: mobile css

- site/src/components/Bounty/ChildBountyItem/index.js
- site/src/components/Bounty/ChildBountyItem/styled.js
- site/src/components/ChildBounty/Detail/Meta/Info/InfoSkills.js
- site/src/components/ChildBounty/Import/BountySkills.js
- site/src/components/Skill/List.js
- site/src/components/Skill/styled.js
> fix: skill up to 3

- site/package.json
- site/src/components/ChildBounty/Detail/Applicants/index.js
- site/src/components/ChildBounty/Detail/Applicants/styled.js
- site/src/components/ChildBounty/Detail/Submission/SubmissionItem.js
- site/src/components/ChildBounty/Detail/Submission/index.js
- site/src/components/ChildBounty/Detail/Submission/styled.js
- site/src/components/ChildBounty/Detail/index.js
- site/src/hooks/useWorkflowActionService.js
- site/yarn.lock
> feat: submission

- site/src/components/ChildBounty/Detail/Meta/Info/InfoParentBounty.js
- site/src/components/ChildBounty/Detail/Meta/Info/index.js
- site/src/components/Ellipsis/index.js
- site/src/components/Ellipsis/styled.js
> fix: child bounty meta info layout

- site/src/components/ChildBounty/Detail/Applicants/index.js
- site/src/components/ChildBounty/Detail/Applicants/styled.js
> fix: applicant mobile css

- site/src/components/Bounty/Detail/index.js
- site/src/components/ChildBounty/Detail/index.js
> fix: remove detail page gap

- site/src/components/Bounty/Import/styled.js
> fix: page bounty import gap

- site/src/components/ChildBounty/Import/index.js
- site/src/hooks/useDifferentNetworkNotice.js
> fix: different network import bounty notice

- site/src/components/Bounty/Import/styled.js
- site/src/components/Bounty/styled/bounty.js
- site/src/components/ChildBounty/Import/BountySkills.js
- site/src/components/ChildBounty/Import/index.js
- site/src/components/Common/Import/BountyMeta.js
> fix: ui reviewed

- site/package.json
- site/src/components/Bounty/BountyItem.js
- site/yarn.lock
> fix: UI reviewed 2

- backend/packages/server/src/services/child-bounty.service/getChildBounties.js
- site/src/components/Bounty/ChildBountyItem/index.js
- site/src/services/chainApi.js
> Hotfix: child bounty list logo should follow the parent bounty

- site/src/components/ChildBounty/Detail/Meta/Title.js
- site/src/components/ChildBounty/Detail/Meta/actions/index.js
- site/src/store/reducers/childBountyDetailSlice.js
- site/src/utils/constants.js
> feat: curator hunter view

- site/package.json
- site/src/components/ChildBounty/Detail/Meta/Title.js
- site/yarn.lock
> fix: curator view select

- .github/workflows/front-ci.yml
- site/package.json
- site/yarn.lock
> fix: pin `semantic-ui-css` to 2.4.1, and add CI
